### ISSUE TITLE
Pingdom::Error (Missing application key. Please see the documentation. (403 Forbidden)):

### ISSUE THREAD

**Issue by treeder** [mtodd/pingdom-client#3]
It needs the application key, but your gem doesn't seem to support that.

**Comment by treeder** [comment]
Btw, this makes your gem unusable it seems.

**Comment by mtodd** [comment]
Hmm, they mentioned having until April 11th to fix this, seems like they've changed their mind. I'll fix this tomorrow.

**Comment by mtodd** [comment]
Require App-Key as :key client option. Closed by 4d462de088adcdc4b2b7c27ec7f5b7f8d7a558ee
